# Generated by Django 4.1.7 on 2023-03-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.CharField(choices=[('Done', 'done'), ('Pause', 'pause')], max_length=20),
        ),
    ]
